[build]
  builder = "nixpacks"
  buildCommand = "npm install && npm run build"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/api/v1/health"
  healthcheckTimeout = 15
  restartPolicyMaxRetries = 3
